liip_imagine:
    # At un comment for AWSS3
    # cache: resolver_local
    # data_loader: import
    resolvers:
        default:
          web_path: ~
    filter_sets:
        keyword:
            quality: 100
            filters:
                thumbnail: { size: [188, 188], mode: outbound }
