twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        admin_locales: '%admin.locales.available%'
        app_locales: '%app.locales.available%'
    form_themes:
        - 'admin/form_div_layout.html.twig'
