# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: "fr"
    app.locales: "en|fr"
    app.cache_lifetime: 84400
    app.locales.available: ["fr", "en"]
    admin.locales: "en|fr"
    admin.locales.available: ["en", "fr"]
    validator.translation_domain: 'app'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php,Query,Repository}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Listener\GaufretteListener:
      arguments:
          $fileSystem: '@knp_gaufrette.filesystem_map'
      tags:
          - { name: doctrine.event_listener, event: postLoad, method: postLoad, priority: 100  }
          - { name: doctrine.event_listener, event: preUpdate, method: preUpdate, priority: 100  }
          - { name: doctrine.event_listener, event: prePersist, method: prePersist, priority: 100  }
          - { name: doctrine.event_listener, event: preRemove, method: preRemove, priority: 100  }
    # Extension
    App\Form\Extension\ImageExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
    App\Twig\InjectExtension:
        arguments:
            $fileSystem: "@knp_gaufrette.filesystem_map"
        tags:
            - { name: twig.extension }
    App\Services\Core\CacheService:
        arguments:
            $lifeTime: '%app.cache_lifetime%'
            $cacheFolder: '%kernel.cache_dir%'
    authentication_handler:
        class: App\Handler\AuthenticationHandler
